src/Entity/Chaine.php
<?php

namespace App\Entity;

use App\Repository\ChaineRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ChaineRepository::class)]
class Chaine
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $Libelle = null;

    #[ORM\Column(length: 200)]
    private ?string $Diffuseur = null;

    #[ORM\OneToMany(mappedBy: 'Chaine', targetEntity: Video::class)]
    private Collection $videos;

    public function __construct()
    {
        $this->videos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): static
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    public function getDiffuseur(): ?string
    {
        return $this->Diffuseur;
    }

    public function setDiffuseur(string $Diffuseur): static
    {
        $this->Diffuseur = $Diffuseur;

        return $this;
    }

    /**
     * @return Collection<int, Video>
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): static
    {
        if (!$this->videos->contains($video)) {
            $this->videos->add($video);
            $video->setChaine($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): static
    {
        if ($this->videos->removeElement($video)) {
            // set the owning side to null (unless already changed)
            if ($video->getChaine() === $this) {
                $video->setChaine(null);
            }
        }

        return $this;
    }
}

src/Entity/Video.php
<?php

namespace App\Entity;

use App\Repository\VideoRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VideoRepository::class)]
class Video
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 175)]
    private ?string $Titre = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $Image = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Date_publication = null;

    #[ORM\ManyToOne(inversedBy: 'videos')]
    private ?Chaine $Chaine = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): static
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): static
    {
        $this->Image = $Image;

        return $this;
    }

    public function getDatePublication(): ?\DateTimeInterface
    {
        return $this->Date_publication;
    }

    public function setDatePublication(\DateTimeInterface $Date_publication): static
    {
        $this->Date_publication = $Date_publication;

        return $this;
    }

    public function getChaine(): ?Chaine
    {
        return $this->Chaine;
    }

    public function setChaine(?Chaine $Chaine): static
    {
        $this->Chaine = $Chaine;

        return $this;
    }
}

src/Form/ChaineType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChaineType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Libelle')
            ->add('Diffuseur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Form/RechercheType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RechercheType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('field_name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/AccueilController.php
<?php

namespace App\Controller;

use App\Entity\Chaine;
use App\Repository\ChaineRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AccueilController extends AbstractController
{
    #[Route('/', name: 'app_accueil')]
    public function index(
        EntityManagerInterface $entityManager,
        ChaineRepository $ChaineRepository)    {

        $listeChaine = $ChaineRepository->findAll();

        return $this->render('accueil/index.html.twig', [
            'listeChaine' => $listeChaine,
        ]);
    }
}

src/Controller/ChaineController.php
<?php

namespace App\Controller;

use App\Entity\Chaine;
use App\Form\ChaineType;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\ChaineRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ChaineController extends AbstractController
{

    #[Route('/chaine/id', name: 'chaineid')]
    public function chaineid( EntityManagerInterface $entityManager,
    ChaineRepository $ChaineRepository)    {

    $listeChaineVideo = $ChaineRepository->findBy($where, $order, $limit, $offset);

    return $this->render('chaine/id.html.twig', [
        'listeChaineVideo' => $listeChaineVideo,
    ]);
    }

    #[Route('/chaine/ajouter', name: 'ajouter')]
    public function ajouter(Request $request, EntityManagerInterface $entityManager): Response
    {
        $Chaine = new Chaine();
        $form = $this->createForm(ChaineType::class, $Chaine);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->persist($Chaine);
            $entityManager->flush();

            return $this->redirectToRoute('app_accueil');
        }
    
        return $this->render('chaine/ajouter.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/chaine/editer/{id}', name: 'editer')]
    public function editer(Request $request, EntityManagerInterface $entityManager, ChaineRepository $ChaineRepository, $id): Response
    {

    $chaine = $ChaineRepository->find($id);

    $form = $this->createForm(ChaineType::class, $chaine);

    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
       
        $entityManager->flush();

        return $this->redirectToRoute('app_accueil');
    }

    return $this->render('chaine/editer.html.twig', [
        'form' => $form->createView(),
    ]);
    }

}

src/Controller/RechercheController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RechercheController extends AbstractController
{
    #[Route('/recherche', name: 'app_recherche')]
    public function index(): Response
    {
        return $this->render('recherche/index.html.twig', [
            'controller_name' => 'RechercheController',
        ]);
    }
}

src/Controller/VideosController.php
<?php

namespace App\Controller;

use App\Entity\Video;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\VideoRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class VideosController extends AbstractController
{
    #[Route('/videos', name: 'app_video')]
    public function index(
        EntityManagerInterface $entityManager,
        VideoRepository $VideoRepository)    {

        $listeVideo = $VideoRepository->findAll();

        return $this->render('videos/index.html.twig', [
            'listeVideo' => $listeVideo,
        ]);
    }
}

templates/accueil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}
<h1>Accueil</h1>
<br>
{% for chaine in listeChaine %}
<div>
    <h3>#{{chaine.id}} - {{ chaine.libelle }} </h3>
    <p>{{ chaine.diffuseur}} </p>
</div>
{% endfor %}
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        {% block stylesheets %}
            {{ ux_controller_link_tags() }}
        {% endblock %}

        {% block javascripts %}
{% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <body>
    <nav>
        <ul>
            <li><a href="{{ path('app_accueil') }}">Accueil</a></li>
	        <li><a href="{{ path('app_video') }}">Video</a></li>
            <li><a href="{{ path('app_recherche') }}">Recherche</a></li>        </ul>
	</nav>
        {% block body %}{% endblock %}
    </body>
</html>

templates/chaine/ajouter.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter Chaine{% endblock %}

{% block body %}
    <div class="container">
        <h1>Ajouter Chaine</h1>
        <div class="row">
            <div class="col-md-6">
                {{ form_start(form, {'attr': {'class': 'form-group'}}) }}
                    <div class="mb-3">
                        {{ form_label(form.Libelle, 'Libellé', {'label_attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.Libelle, {'attr': {'class': 'form-control'}}) }}
                    </div>
                    <div class="mb-3">
                        {{ form_label(form.Diffuseur, 'Diffuseur', {'label_attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.Diffuseur, {'attr': {'class': 'form-control'}}) }}
                    </div>
                    <button type="submit" class="btn btn-primary">Créer</button>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/chaine/editer.html.twig
{# modifier.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Editer Chaine{% endblock %}

{% block body %}
    <h1>Editer Chaine</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                {{ form_start(form) }}
                    {{ form_widget(form) }}
                    <button type="submit" class="btn btn-primary">Enregistrer</button>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/chaine/id.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chaines & Videos{% endblock %}

{% block body %}
<h1>Chaine & Vidéos</h1>
<br>
{% for chaine in listeChaine %}
<div>
    <h3>#{{chaine.id}} - {{ chaine.libelle }} </h3>
    <p>{{ chaine.diffuseur}} </p>
</div>
{% endfor %}
{% endblock %}

templates/recherche/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello RechercheController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/var/www/tpnote/src/Controller/RechercheController.php'|file_link(0) }}">src/Controller/RechercheController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/var/www/tpnote/templates/recherche/index.html.twig'|file_link(0) }}">templates/recherche/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/videos/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Videos{% endblock %}

{% block body %}
<h1>Videos</h1>
<br>
{% for video in listeVideo %}
<div>
    <h3>#{{video.id}} - {{ video.titre }} </h3>
    <p>{{ video.image}} </p>
    <p>{{ video.datePublication|date('d/m/y')}} </p>
</div>
{% endfor %}
{% endblock %}